language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
before_script:
- npm install web-component-tester
- npm install -g bower
- bower install
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: nrIrTfbt2AYVmk5BGRA7JozHXVI+DZ1Bw2L4jHLoE9Fy+IAJCFDhNrby5iYc7VFTFzusL5627+cfP11nlVjJtF7blI22un6cP4drhK4YrAV1tZxVr88mTcj7haZqNSQDHPxEhdDweOLejFeJIrFqQ+3oab47ChdNaotAq+7C9wqL/5BbN3JZ5MiJRFCoFcj3M2TCdRxFcuzNzHt2sAK83zPKFrrZIgY2YgsA34I6LULzON4+k3EXStCY1banwqFBz7iG8m0trW0NUUGbx10BAlPpdXJisLNQdEYNLZnwWTWhNvyG6lqU72ad+IAAyw/lsTptePUy9+lesk4Aa6ejsF3NPGYxnI//x6sjz6y7p7FDFd71BjgmW4oTph+Vnm2gMtdmQqkLAHs3HhHu1gsi6oNuz0KMp8QV9gXIVcySRt5V82W7wcwzzo1muCxRzoyxg35MRfY1oHtorm/jdiYuyPw63n+UtcUpnOD4u5uUNyFT4JDF+evGm3sN/XAWBCkjfoFNsXtENRdg71kVFVrPGc1QLT4lEwuzb6+uc7itBK/2rYEyY75pc1hHAIB9EEhcWbKcwuHcGKIxAC/vEv9SiW/Wb6KuXsS5aCjgKbjEpX2I+K/P/VmwyOJQNfdAT4juK+yg9Zj5QYMWgfp+8RiXmyfi3/Wn8zOOSSrS6kSA7b4=
  - secure: HF1uvs4puj3lvMvEak3jBzv17oF/xGYObDXHT4kE7e82Y/zvfoYmt5VvvEjL8MpNmR4lgEmzygXXmhoSTAWuHpfW2sOMkrr6DcRJSexbFSZ1DPeXq2S2YQDOeyr8qKCaB28FQ7dWlpI1LGY/nP1A5gZgIOOYwSCuqkfhftEvy1MgD3q2oCzqU4AZwEupSOkjJ4IPr71g8ZRaxyGZOo47lNOXusIZqkKuaFcHyjT0Rr3F2/Qi6EebzORrDbyJ81m6Zgbk7hJRkPwRNZ7Qi3gX/Rxzmqc9Fm+ZNskjwSrz7cq4Icc+r8Jlg0qUj+LlHMK88/kps58vG/BZLU/+risNIbd1VjPRc9kk/3I8cUyJuK509jsaDH6TVLbyHaK+MaQotg/MjGhZqX+6m+HAD+HYgSDxXiLThOEgDVZpjVUfEBmtzhvrINzva/aO0NmbwjDEKqHBe0Qs0b1XNcRNgC8CovO8QIefEL4O55x7XIVv+rQgAcyXidMmTf+3ZUaZtYjCBqNlsUqnRTO5wX06ZErFA7sL1KU7VNlzHpkLLq7fLy0Yv4MZ1WhaR308Wkca951UehkSeRByW6E3q5R+kMjWOLSr0gf7uaqyV5dgR5/Epht6O7R6VbaEm5Dctfb93L5SBHQ8TX84VEj6rs8fX6IcZ70g5woeu5Q3X+gQrIK0Rvw=
